name: CI


# We want to build on all branches and pull requests
#
# @see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Prepare build environment
    - name: Prepare build environment
      run: npx --package mini-cross mc --no-tty _ make clean

    # Native compilation, test and upload
    - name: Native Build
      run: npx --package mini-cross mc --no-tty _ make clean native

    - name: Upload native artifact
      uses: actions/upload-artifact@v2
      with:
        name: Ubuntu 20.04 amd64
        path: build-native/binary-patch/binary-patch/executable/binary-patch-binary-patch-executable
        if-no-files-found: error

    # Cross compilation, test and upload
    - name: Windows Build
      run: npx --package mini-cross mc --no-tty _ make clean windows

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows amd64
        path: build-windows/binary-patch/binary-patch/executable/binary-patch-binary-patch-executable.exe
        if-no-files-found: error
